In [1]:
import os
import pandas as pd
from google.cloud import bigquery

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\api_core\_python_version_support.py:246: FutureWarning: You are using a non-supported Python version (3.9.25). Google will not post any further updates to google.api_core supporting this Python version. Please upgrade to the latest Python version, or at least Python 3.10, and then update google.api_core.
  warnings.warn(message, FutureWarning)
c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\auth\__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\oauth2\__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

In [2]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r"C:\Users\migue\Downloads\Miguel Jaimes\lihki-490802-d49b7d8420b9.json"

In [3]:
client = bigquery.Client()

In [4]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.accidentes` LIMIT 5"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,incidente_id,fecha,barrio_id,tipo,gravedad,heridos,fallecidos,clima,causa
0,9,2024-08-25,1,moto,leve,0,0,lluvia,exceso_velocidad
1,27,2024-04-09,1,choque,leve,3,0,lluvia,exceso_velocidad
2,65,2024-03-24,1,moto,grave,2,0,seco,exceso_velocidad
3,82,2024-02-20,1,atropello,leve,1,0,lluvia,exceso_velocidad
4,89,2024-07-09,1,atropello,leve,3,0,seco,exceso_velocidad

In [5]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.barrio` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,barrio_id,barrio,comuna,poblacion,estrato_promedio,lat,lon
0,2,La Esperanza,1,8300,2,11.006,-74.804
1,4,San José,2,7200,2,11.008,-74.797
2,7,La Pradera,4,7800,2,11.007,-74.792
3,9,Nueva Colombia,5,8600,2,11.015,-74.798
4,1,Centro,1,10500,3,11.004,-74.801
5,3,Villa Norte,2,9400,3,11.010,-74.799
6,6,Altos del Río,3,6500,3,11.013,-74.803
7,8,El Bosque,4,9800,3,11.011,-74.795
8,10,Mirador,5,7200,3,11.016,-74.801
9,5,Los Almendros,3,11500,4,11.012,-74.806

In [6]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.hogares` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,hogar_id,barrio_id,estrato,tamano_hogar,ingreso_mensual,sisben,adultos_mayores,ninos
0,30,1,1,2,1848438,A,0,0
1,246,1,2,2,1794451,C,2,2
2,269,1,2,2,1875902,B,1,0
3,536,1,2,2,1056725,B,1,0
4,542,1,2,2,2139782,B,0,2
...,...,...,...,...,...,...,...,...
995,581,10,4,6,2021694,C,0,3
996,586,10,3,6,2299610,A,1,1
997,640,10,4,6,1678530,B,2,2
998,760,10,3,6,2313087,A,1,2
999,838,10,3,6,1726116,A,1,0

In [7]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.indicadores_sociales` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,periodo,barrio_id,desempleo,desercion_escolar,cobertura_salud,acceso_internet
0,2024,2,0.21,0.03,0.77,0.67
1,2024,4,0.11,0.03,0.77,0.73
2,2024,9,0.12,0.09,0.78,0.65
3,2024,1,0.12,0.02,0.80,0.60
4,2024,7,0.20,0.06,0.80,0.68
5,2024,3,0.10,0.06,0.81,0.50
6,2024,10,0.10,0.06,0.83,0.58
7,2024,8,0.21,0.06,0.84,0.69
8,2024,6,0.15,0.07,0.86,0.74
9,2024,5,0.19,0.09,0.88,0.79

In [8]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.obras_publicas` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,obra_id,barrio_id,tipo,presupuesto,avance_fisico,avance_financiero,estado,retraso_dias
0,27,2,alcantarillado,4967000000,73,68,en_ejecucion,19
1,8,3,alcantarillado,2358000000,16,10,en_ejecucion,2
2,17,3,alcantarillado,3881000000,90,100,en_ejecucion,15
3,20,3,alcantarillado,2799000000,27,44,retrasada,99
4,44,5,alcantarillado,1063000000,55,54,en_ejecucion,4
5,4,6,alcantarillado,381000000,40,33,en_ejecucion,8
6,16,6,alcantarillado,4619000000,67,63,en_ejecucion,17
7,21,6,alcantarillado,956000000,100,100,en_ejecucion,12
8,39,7,alcantarillado,2089000000,90,96,en_ejecucion,11
9,47,7,alcantarillado,4204000000,53,71,retrasada,117
10,50,8,alcantarillado,3086000000,12,18,en_ejecucion,17
11,2,9,alcantarillado,2883000000,17,15,en_ejecucion,1
12,36,1,colegio,474000000,67,61,en_ejecucion,14
13,48,1,colegio,2007000000,32,41,en_ejecucion,9
14,31,2,colegio,2635000000,82,73,en_ejecucion,0
15,38,2,colegio,749000000,60,63,en_ejecucion,4
16,18,3,colegio,1708000000,2,15,en_ejecucion,16
17,43,4,colegio,1239000000,1,11,en_ejecucion,19
18,11,5,colegio,4335000000,5,8,en_ejecucion,15
19,15,5,colegio,2552000000,7,25,retrasada,66
20,19,5,colegio,4250000000,16,27,en_ejecucion,18
21,7,8,colegio,1444000000,33,37,en_ejecucion,19
22,13,10,colegio,3202000000,12,13,en_ejecucion,19
23,14,1,parque,3087000000,59,71,en_ejecucion,17
24,29,1,parque,3657000000,51,41,en_ejecucion,8
25,26,2,parque,1631000000,31,50,retrasada,35
26,46,2,parque,4066000000,22,26,en_ejecucion,15
27,22,3,parque,1714000000,23,40,retrasada,44
28,41,3,parque,2523000000,54,46,en_ejecucion,14
29,3,4,parque,1167000000,8,9,en_ejecucion,7
30,5,4,parque,1122000000,74,84,en_ejecucion,3
31,6,5,parque,704000000,66,83,retrasada,56
32,12,7,parque,2011000000,30,44,en_ejecucion,5
33,24,7,parque,2756000000,57,52,en_ejecucion,17
34,25,7,parque,2363000000,23,33,en_ejecucion,0
35,42,7,parque,2126000000,86,79,en_ejecucion,6
36,9,9,parque,2383000000,80,95,en_ejecucion,10
37,34,9,parque,1401000000,20,19,en_ejecucion,14
38,33,10,parque,2312000000,47,61,en_ejecucion,6
39,23,1,pavimentacion,4668000000,23,24,en_ejecucion,20
40,28,1,pavimentacion,3720000000,50,45,en_ejecucion,14
41,40,1,pavimentacion,4989000000,41,38,en_ejecucion,14
42,35,2,pavimentacion,2120000000,48,65,retrasada,0
43,49,3,pavimentacion,2572000000,54,69,en_ejecucion,2
44,1,4,pavimentacion,336000000,73,81,en_ejecucion,5
45,32,4,pavimentacion,708000000,94,100,en_ejecucion,2
46,45,4,pavimentacion,3487000000,44,42,en_ejecucion,9
47,30,6,pavimentacion,3259000000,55,51,en_ejecucion,5
48,37,8,pavimentacion,2924000000,51,49,en_ejecucion,12
49,10,9,pavimentacion,1777000000,94,100,en_ejecucion,0

In [9]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.pqr` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,pqr_id,fecha,barrio_id,tipo,canal,secretaria,dias_respuesta,estado,satisfaccion
0,23,2024-01-23,1,vias,telefono,gobierno,1,abierto,5
1,136,2024-03-31,1,alcantarillado,web,infraestructura,1,cerrado,3
2,528,2024-06-12,1,iluminacion,app,infraestructura,1,abierto,2
3,594,2024-10-16,1,agua,web,infraestructura,1,abierto,1
4,767,2024-04-28,1,agua,telefono,servicios_publicos,1,cerrado,3
...,...,...,...,...,...,...,...,...,...
995,377,2024-08-29,5,seguridad,app,infraestructura,14,cerrado,5
996,741,2024-03-03,5,vias,web,infraestructura,14,cerrado,5
997,786,2024-08-15,5,ruido,telefono,servicios_publicos,14,cerrado,5
998,1407,2024-03-17,5,iluminacion,web,servicios_publicos,14,cerrado,2
999,1526,2024-12-14,5,vias,telefono,infraestructura,14,cerrado,2

In [10]:
sql_query = "SELECT * FROM `lihki-490802.Prototipo.predial` LIMIT 1000"
query_job = client.query(sql_query).to_dataframe()
query_job

c:\Users\migue\miniconda3\envs\seminario\lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,predio_id,barrio_id,avaluo,impuesto,pagado,mora_dias,acuerdo_pago
0,672,10,50000000.0,400000,no,150,si
1,875,1,50000000.0,400000,no,134,si
2,988,4,50000000.0,400000,no,118,no
3,1482,4,50000000.0,400000,no,58,no
4,329,8,52000000.0,416000,no,144,si
...,...,...,...,...,...,...,...
995,853,3,132000000.0,1056000,si,0,no
996,937,3,132000000.0,1056000,si,0,no
997,1402,2,132000000.0,1056000,si,0,no
998,114,9,133000000.0,1064000,si,0,no
999,649,2,133000000.0,1064000,si,0,no